version: '3.8'

services:
  frameweaver:
    image: frameweaver
    container_name: frameweaver
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "1883:1883"
      - "8080:8080"
